### ISSUE TITLE
Files from different deliveries zipped together

### ISSUE THREAD

**Issue by sivertschou** [devilry/devilry-django#1120] opened 2019-09-09 09:01 UTC
I have been correcting some assignments and I noticed that when a student delivers multiple deliveries with files with different names, the downloaded assignment-zip will contain all the files in the same directory, with no indication of which delivery it was. It would be nice to have all these files separated into delivery folders, or at least an option to do this. 
I get that the mechanism might be useful if a student forgets to upload a file, but I don't think devilry is used like that.

Example:
Delivery 1: `oblig1.java`
Delivery 2: `Oblig1.java`
Delivery 3: `Oblig1.zip`

Downloaded assignment zip after pressing the `Download: first deadline`-button:
```
oblig1.java
Oblig1.java
Oblig1.zip
```

**Comment by torgeirl** [comment] 2019-09-09 10:38
Hi @sivertschou! Thank for providing feedback.

This is working as intended: any duplicate («re-upload») gets archived in a directory while the latest of every file is presented to the examiner(s) as the delivery. And I don't think we will diverge from this model.

With the use case you present, I do however see some improvements we could explore:
- warn students when a file name only differentiate by capitalization
- allow students to archive older uploads manually

If both gets implemented, the warning dialog could give the student the option whether they want to archive the older file or keep both.

**Comment by Levijatan** [comment] 2024-02-27 11:28
So force lowercase when checking for duplicates when choosing what files to add to the zip?

**Comment by torgeirl** [comment] 2024-02-27 11:42
> So force lowercase when checking for duplicates when choosing what files to add to the zip?

I believe `casefold()` is a little safer since it should work for more special character scenarios (ie. ß==ss).

**Comment by Levijatan** [comment] 2024-02-28 09:53
Commited fix for this issue in 4b7965e. Ended up using `casefold()`. Also changed naming scheme for older duplicates to match date scheme in #1071

**Closed** 2024-04-12 07:32 UTC
