### ISSUE TITLE
Zip files for examiners aren't remade after changes

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#982] opened 2018-02-23 17:10 UTC
There seems to still be issues with the Zip files for examiners. `v3.1.4` addressed the problem with Zip files not being unique to multiple examiners on the same assignment (issue #977), but examiners still report have issues with the content of the files.

Some report the files not getting generated, but I haven't been able to reproduce that yet.

I have however seen that if I assign new students to myself as examiner, the file isn't reproduced, so things are still not working as intended.

**Workaround**
Not ideal, but from `v3.1.4` it's possible to delete Zip files N seconds old, limiting the problem if you don't have to many examiners per subject:
`*/5 * * * * /devilry/venv/bin/python /devilry/manage.py devilry_delete_compressed_archives --seconds 180`

**Comment by StianJul** [comment] 2018-02-26 10:20
> I have however seen that if I assign new students to myself as examiner, the file isn't reproduced, so things are still not working as intended.

Maybe I misunderstand, but when you add a new student to an examiner, a compressed archive won't be generated again unless a new file is added in any of the groups the examiner has access to on the assignment. That is the intended behaviour :-)

**Comment by StianJul** [comment] 2018-02-26 10:25
I see now, the student added already has files from before. We're discussing a fix for this.

**Comment by torgeirl** [comment] 2018-02-26 10:25
> I see now, the student added already has files from before. We're discussing a fix for this.
Yes, exactly. :+1:

**Comment by StianJul** [comment] 2018-02-26 10:47
We're gonna add two new "log"-tables to handle this, one that logs if an examiner is added/removed from the group, and the same for a student. This will make it easy to see if something has happened to assignment group since the last archive was generated.

With these two new "logging"-tables we can also add more event information to the feedbackfeed in the future. Such as "<examiner> joined/left the group" and same for students.

**Comment by torgeirl** [comment] 2018-02-27 10:33
@StianJul: would you be able to fix #984 by a similar logging table fix?

**Comment by StianJul** [comment] 2018-02-27 11:04
> @StianJul: would you be able to fix #984 by a similar logging table fix?

I've answered this in #984.

**Closed** 2018-03-01 09:54 UTC
Labels: ready
