### ISSUE TITLE
Displaying a list of group members on a delivery

### ISSUE THREAD

**Issue by NotoriousBIB** [devilry/devilry-django#773] opened 2015-06-10 20:48 UTC
It would be nice to have a list of other group members when looking at open assignments, deliveries and feedbacks. Or at least an icon indicating that this is a group delivery.

**Comment by espenak** [comment] 2015-06-10 20:50
This is a duplicate of #737. #737 will be fixed during the summer.

**Comment by espenak** [comment] 2015-06-10 20:51
Ahh or perhaps you mean in the examiner UI?

**Comment by torgeirl** [comment] 2022-02-15 11:55
We still need to make group and individual assignments more visually distinguishable from the student perceptive, but that is handled in #915 so closing this issue.

**Closed by torgeirl** 2022-02-15 11:55 UTC
