### ISSUE TITLE
Semester admin can't access semester

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1240] opened 2022-09-14 10:22 UTC
One semester admin was unable to access the semester page, instead getting «Ingen adgang» («No access» I assume, unsure about the HTTP code; perhaps 302?). The semester didn't have any assignments yet, so nothing that distinguished it from any of our many courses without error. I suspect it might be related to the access issues in #1236.

**Workaround**
It seems promoting the semester admin to course admin fixed the access to the semester.

**Comment by espenak** [comment] 2022-09-16 09:52
@torgeirl I am not able to reproduce this, but as far as I can trace this it must mean that the user is not admin on a period within the subject..

First they will get to the subject redirect view which sends the user to the "subject" page for subject or period admins depending on permissions:
https://github.com/devilry/devilry-django/blob/55c924aa82bd1ba35333818f4f974c72524838d9/devilry/devilry_admin/views/subject_for_period_admin/subject_redirect.py#L15-L24

As period admin they will end up in the ``elif``, and be redirected to the subject overw page for period admins:
https://github.com/devilry/devilry-django/blob/55c924aa82bd1ba35333818f4f974c72524838d9/devilry/devilry_admin/views/subject_for_period_admin/overview_for_periodadmin.py#L28-L52

Here we can see that the permissions are checked again, and they will "pass" if they are period admin within the subject (``get_unfiltered_queryset_for_role()`` method).

**Comment by espenak** [comment] 2022-09-20 09:03
The issue here is most likely that the user it course admin on another course and semester admin on the course with this issue. We had a bug in the SubjectRedirectView where users where sent to the "course admin course page" if they where course admin on ANY course (thus the permission denied page when they where period admin). This is now fixed. Note that this did not give any elevated permissions to anything - it is just a bug in where we redirected people.e

**Closed** 2022-09-20 09:03 UTC
Labels: bugreport-with-missing-info
