### ISSUE TITLE
"Waiting for deliveries" filter is broken

### ISSUE THREAD

**Issue by KGHustad** [devilry/devilry-django#1094] opened 2018-12-05 12:19 UTC
I have 18 groups, 16 should be "waiting for feedback", and 2 should be "waiting for deliveries". However, one of the groups which are waiting for deliveries is not shown when the filter is applied (and hence the sum is also incorrect).

<img width="295" alt="devilry_waiting_for_deliveries_bug" src="https://user-images.githubusercontent.com/11854250/49512943-c1c93180-f88f-11e8-969d-7137b69f3e83.png">

Moreover, when in the main "examiner" menu, the assignment has "17 waiting for feedback", which is not correct either.

**Comment by torgeirl** [comment] 2018-12-05 13:32
Out of his 18 groups, the two `Waiting for deliveries` consists of a 1-person group and a 2-person group. My guess is that the issue is related to the group with two students.

The group issues that were addressed in `3.5.1` mainly had to do with multiple deadlines while the 2-person group here only has one deadline.

**Comment by KGHustad** [comment] 2018-12-07 08:53
It might be relevant that I used the `Move deadline`-button to give an extension to these two groups. I now tried giving these a `Failed` feedback and then a new attempt, and that seems to work as it should.

**Comment by torgeirl** [comment] 2018-12-12 11:39
As I understand it, their status should have been updated with the `3.5.1` patch (devs: I assume that's way [the migration guide](https://devilry.readthedocs.io/en/master/sysadmin/migrationguides/migrate-from-3.5.0-to-3.5.1.html) instruct sysadmins to run `ievvtasks_customsql -i -r` after updating) but it could be it was missed. If so, the problem that resulted in this issue is already solved, but more cases like this could still be present from before the patch got applied.

**Closed** 2019-01-16 10:04 UTC
